version: '3.8'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qa130859
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - 'pgadmin:/var/lib/pgadmin'

volumes:
  pgadmin:
  postgres:

